#%RAML 1.0 DataType

type: object 
description: 
properties:
      movie_id?: integer
      ticket_name?: string
      ticket_price?: string
      ticket_number?: string
      ticket_booked?: boolean
