#%RAML 1.0
title: Book My Show

types:
  Movies:
  Tickets: 

/movies:
  get:
    description: Displays movies that are currently in theatres
    queryParameters:
      Movie Name:
      displayName: 
     Movie ID:
            displayName: Snack ID
            description: Snack ID number 
            required: true
            type: integer
          Movie Type:
            displayName: Movie Name
            description: 
            required: false
            type: string
          Movie Name:
            displayName: Snack Name
            description: Displays the name of the snack
            required: false
            type: string
          Movie Price:
            displayName: Snack Price
            description: Shows the price of the snack in rupees
            required: false
            type: string
        responses:
          200:
            body:
              application/json:
                type: Snacks[]
                example: 
          400:
            body:
              application/json:
                example:
                  message: Error retrieving snack data!

      post:
        displayName: Add new snack
        description: Create a new snack
        body:
          application/json:
            type: Snacks[]
            example: 
        responses:
          201:
            body:
              application/json:
                example:
                  message: New snack created!
          400:
            body:
              application/json:
                example:
                  message: Error creating new snack.

      put:
        description: Update a snack
        body:
          application/json:
            type: 
            example: 
              input:!include 
        responses:
          200:
            body:
              application/json:
                example:
                  message: Snack updated!
              
      delete:
        description: Delete a snack
        responses:
          200:
            body:
              application/json:
                example:
                  message: Snack deleted!

         
      

        
  /tickets: 
      get:
        description: Gets all tickets based on the given query parameters
        queryParameters:
          Ticket ID: 
            displayName: Ticket ID
            description: Ticket ID number 
            required: true
            type: integer
          Ticket Type:
            displayName: Ticket Type
            description: Shows whether it Balcony or First Class ticket
            required: false
            type: string
          Ticket Price:
            displayName: Ticket Price
            description: Displays the price of the ticket in rupees
            required: false
            type: string
          Ticket Number:
            displayName: Ticket Number
            description: Shows the row and seat number of the ticket
            required: false
            type: string
          Ticket Booked:
            displayName: Ticket Booked
            description: Shows whether ticket has been booked
            required: false
            type: string
        responses:
          200:
            body:
              application/json:
                type: Tickets[]
                example: 
          400:
            body:
              application/json:
                example:
                  message: Error retrieving Ticket data!
                  
      post:
        displayName: Add new ticket
        description: Create a new ticket
        body:
          application/json:
            type: Tickets[]
            example:
        responses:
          201:
            body:
              application/json:
                example:
                  message: New ticket created!
          400:
            body:
              application/json:
                example:
                  message: Error creating new ticket.
                  

      put:
        description: Update a ticket
        body:
          application/json:
            type: 
            examples: 
              input: 
        responses:
          200:
            body:
              application/json:
                example:
                  message: Ticket Updated!

      delete:
        description: Delete a ticket
        responses:
          200:   
            body:
              application/json:
                example:
                  message: Ticket deleted!
                  
      /{ticket_id}:
        get:
          description: Find tickets by ID
          responses:
            200:
              body:
                application/json:
                  type: 
                  examples:
                    output: 
                                                              