#%RAML 1.0
title: Book My Show

types:

/tickets:
  description: Retrieves movie tickets 
  get:




  post:


  put:


  delete:
    

/snacks:
  displayName: Retrieves snacks 
  get:


  post:


  put:

  
  delete:

