#%RAML 1.0 NamedExample

value:
  -
      "movie_id": 0
      "movie_title": "The Cat in the Hat"
      "movie_description": "A movie about a cat who wears a red"
      "movie_showtimes": "1200, 1300, 1500"
  -
      "movie_id": 0
      "movie_title": "The Cat in the Hat"
      "movie_description": "A movie about a cat who wears a red"
      "movie_showtimes": "1200, 1300, 1500"