#%RAML 1.0 NamedExample

values:
  -
    "movie_id": 0
    "movie_title": "The Cat in the Hat"
    "movie_description": "A movie about a cat who wears a red hat"
    "movie_showtimes": "1200, 1300, 1500"
  -
    "movie_id": 1
    "movie_title": "The Dog in the Cap"
    "movie_description": "A movie about a cat who wears a red cap"
    "movie_showtimes": "1200, 1300, 1500"