#%RAML 1.0 NamedExample
ticketExample:

type: object 
description: 
properties:
[
{
    "ticket_id": 0,
    "ticket_type": "Balcony",
    "ticket_price": "500.00 INR",
    "ticket_number": A101,
    "ticket_booked": true,
    }
    ]