#%RAML 1.0 NamedExample
ticketExample:

type: object 
description: 
properties:
      ticket_id?: integer
      ticket_type?: string
      ticket_price?: string
      ticket_number?: string
      ticket_booked?: boolean