#%RAML 1.0 NamedExample
ticketExample:

type: object 
description: 
properties:
      "ticket_id": 0
      "ticket_type": "Balcony"
      "ticket_price": "500 r.s"
      "ticket_number": string
      "ticket_booked": boolean