#%RAML 1.0 NamedExample

value:
  -
      "ticket_id": 0
      "ticket_type": "Balcony"
      "ticket_price": "500.00 INR"
      "ticket_number": "A101"
      "ticket_booked": true
  -
      "ticket_id": 1
      "ticket_type": "Balcony"
      "ticket_price": "400.00 INR"
      "ticket_number": "A101"
      "ticket_booked": true